export const FETCH_POST = 'FETCH_POST';

export const LIVE_SCORE = 'LIVE_SCORE';

export const GET_IMAGES = 'GET_IMAGES';
export const GET_SCORECARD = 'GET_SCORECARD';
export const MATCH_DETAIL = 'MATCH_DETAIL';
export const PLAYERS_BY_MATCH = 'PLAYERS_BY_MATCH';
export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_BAT_BOWL = 'GET_BAT_BOWL';

export const FETCH_ALL_SERIES = 'FETCH_ALL_SERIES';
export const FETCH_SERIES_TEAMS = 'FETCH_SERIES_TEAMS';
export const RESET_SERIES = 'RESET_SERIES';
export const FETCH_SERIES_STANDINGS = 'FETCH_SERIES_STANDINGS';

export const FETCH_SCORE_PREDICTION = 'FETCH_SCORE_PREDICTION';








export const DL_TARGET_SCORE_PREDICTION = "DL_TARGET_SCORE_PREDICTION";
export const PAR_SCORE_PREDICTION = "PAR_SCORE_PREDICTION";

export const INNINGS_DETAIL = "INNINGS_DETAIL";
export const RESET_MATCH_DETAILS = "RESET_MATCH_DETAILS";
export const RESET_PREDICTOR = "RESET_PREDICTOR";
export const RESET_PARSCORE = "RESET_PARSCORE";
export const RESET_TARGETSCORE = "RESET_TARGETSCORE";

